# Dataset Settings
dataset: cifar100
num_classes: 100
imb_type: exp
imb_factor: 0.01
data_path: ./data
classifier: dot_product_classifier
augmentation: weak

# Selection Settings (SAVA) – ratio will be overridden by train.py sweep
selection_method: sava
selection_ratio: 0.7
device: cuda
sava_batch_size: 5000
sava_cache_label_distances: true

# Noise
noise_first: false
noise_ratio: 0.0

# Training Strategy
strategy: DeepSMOTE_Sava
loss_type: CE
train_rule: null
base_strategy: ERM

# Hyperparameters
epochs: 200
start_epoch: 0
print_freq: 10
batch_size: 128
learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0002
lr_steps: [120, 160]
gamma: 0.1
rand_number: 0
mixup_alpha: 1.0
workers: 4
optimizer: sgd

# Logging & Checkpoints
root_log: results_sava/cifar100/cifar100_exp0.01_deepSMOTE
root_model: ./checkpoint_cifar100
store_name: cifar100_deepSMOTE_sava_0.7_weak
cifar_root: ./data
gpu: 0
seed: 42