augmentation: weak
base_strategy: ERM
batch_size: 128
cifar_root: ./data
classifier: dot_product_classifier
data_path: ./data
dataset: cifar10
device: cuda
epochs: 200
gamma: 0.1
gpu: 1
imb_factor: 0.01
imb_type: exp
learning_rate: 0.1
loss_type: CE
lr_steps:
- 120
- 160
momentum: 0.9
noise_first: false
noise_ratio: 0.15
num_classes: 10
optimizer: sgd
print_freq: 10
rand_number: 0
root_log: results_sava/cifar10_exp0.01_noisy0.15_randOversamp/sava
root_model: ./example/checkpoint_cifar10
sava_batch_size: 5000
sava_cache_label_distances: true
seed: 42
selection_method: sava
selection_ratio: 0.5
start_epoch: 0
store_name: cifar10_sava_selection_0.7_randOversamp_exp0.01_ratio0.5
strategy: RandomOversampling_Selection
train_rule: None
weight_decay: 2e-4
workers: 4
