augmentation: weak
base_strategy: ERM
batch_size: 128
cap_per_class: 4000
cifar_root: ./data
classifier: dot_product_classifier
data_path: ./data
dataset: cifar10
device: cuda
epochs: 200
gamma: 0.1
gpu: 0
imb_factor: 0.01
imb_type: exp
learning_rate: 0.1
loss_type: CE
lr_steps:
- 120
- 160
momentum: 0.9
noise_ratio: 0.25
num_classes: 10
optimizer: sgd
print_freq: 10
rand_number: 0
root_log: experiments/cifar10_exp0.01_noisy_randOversamp/lava
root_model: ./example/checkpoint_cifar10
seed: 42
selection_method: lava
selection_ratio: 1.0
start_epoch: 0
store_name: cifar10_lava_selection_0.7_mixup_exp0.01_ratio1.0
strategy: RandomOversampling_Selection
train_rule: None
weight_decay: 2e-4
workers: 4
