augmentation: weak
batch_size: 128
cifar_root: ./data
classifier: dot_product_classifier
data_path: ./data
dataset: cifar10
device: cuda
epochs: 200
gamma: 0.1
gpu: 0
imb_factor: 0.01
imb_type: exp
learning_rate: 0.1
loss_type: CE
lr_steps:
- 120
- 160
mixup_alpha: 1.0
momentum: 0.9
num_classes: 10
optimizer: sgd
print_freq: 10
rand_number: 0
root_log: experiments/cifar10_exp0.01/random
root_model: ./example/checkpoint_cifar10
seed: 42
selection_method: random
selection_ratio: 0.3
start_epoch: 0
store_name: cifar10_model_ratio0.3
strategy: ERM
train_rule: None
weight_decay: 2e-4
workers: 4
